//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mayLocNuocEntitiesNhaCungCap : DbContext
    {
        public mayLocNuocEntitiesNhaCungCap()
            : base("name=mayLocNuocEntitiesNhaCungCap")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acc> accs { get; set; }
        public virtual DbSet<chucvu> chucvus { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<gioithieu> gioithieux { get; set; }
        public virtual DbSet<info> infoes { get; set; }
        public virtual DbSet<infodelete> infodeletes { get; set; }
        public virtual DbSet<liKe1> liKe1 { get; set; }
        public virtual DbSet<liKedg> liKedgs { get; set; }
        public virtual DbSet<loai> loais { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        [DbFunction("mayLocNuocEntitiesNhaCungCap", "F_cungHang")]
        public virtual IQueryable<F_cungHang_Result> F_cungHang(Nullable<int> idsp)
        {
            var idspParameter = idsp.HasValue ?
                new ObjectParameter("idsp", idsp) :
                new ObjectParameter("idsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_cungHang_Result>("[mayLocNuocEntitiesNhaCungCap].[F_cungHang](@idsp)", idspParameter);
        }
    
        [DbFunction("mayLocNuocEntitiesNhaCungCap", "F_HienThiTatCarTaiKhoan")]
        public virtual IQueryable<F_HienThiTatCarTaiKhoan_Result> F_HienThiTatCarTaiKhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_HienThiTatCarTaiKhoan_Result>("[mayLocNuocEntitiesNhaCungCap].[F_HienThiTatCarTaiKhoan]()");
        }
    
        [DbFunction("mayLocNuocEntitiesNhaCungCap", "F_layComment")]
        public virtual IQueryable<F_layComment_Result> F_layComment(Nullable<int> idDG)
        {
            var idDGParameter = idDG.HasValue ?
                new ObjectParameter("idDG", idDG) :
                new ObjectParameter("idDG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layComment_Result>("[mayLocNuocEntitiesNhaCungCap].[F_layComment](@idDG)", idDGParameter);
        }
    
        [DbFunction("mayLocNuocEntitiesNhaCungCap", "F_laydanhdia")]
        public virtual IQueryable<F_laydanhdia_Result> F_laydanhdia(Nullable<int> idsp)
        {
            var idspParameter = idsp.HasValue ?
                new ObjectParameter("idsp", idsp) :
                new ObjectParameter("idsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_laydanhdia_Result>("[mayLocNuocEntitiesNhaCungCap].[F_laydanhdia](@idsp)", idspParameter);
        }
    
        [DbFunction("mayLocNuocEntitiesNhaCungCap", "F_laySanPham")]
        public virtual IQueryable<F_laySanPham_Result> F_laySanPham(Nullable<int> idsp)
        {
            var idspParameter = idsp.HasValue ?
                new ObjectParameter("idsp", idsp) :
                new ObjectParameter("idsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_laySanPham_Result>("[mayLocNuocEntitiesNhaCungCap].[F_laySanPham](@idsp)", idspParameter);
        }
    
        [DbFunction("mayLocNuocEntitiesNhaCungCap", "F_Top10DanhGiaCao")]
        public virtual IQueryable<F_Top10DanhGiaCao_Result> F_Top10DanhGiaCao(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_Top10DanhGiaCao_Result>("[mayLocNuocEntitiesNhaCungCap].[F_Top10DanhGiaCao](@top)", topParameter);
        }
    
        [DbFunction("mayLocNuocEntitiesNhaCungCap", "F_TopBanChay")]
        public virtual IQueryable<F_TopBanChay_Result> F_TopBanChay(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_TopBanChay_Result>("[mayLocNuocEntitiesNhaCungCap].[F_TopBanChay](@top)", topParameter);
        }
    
        public virtual int P_themtaikhoan(string taikhoan, string matkhau, string email, ObjectParameter themtaikhoantrave)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_themtaikhoan", taikhoanParameter, matkhauParameter, emailParameter, themtaikhoantrave);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
